# docker-compose.yml
version: '3'

services:

  # MySQL database
  db-svc:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db-data-mariadb:/var/lib/mysql
    networks:
      - net-wp
    ports:
      - 3306:3306

  # Wordpress
  wp:
    image: fernan2/wp_unit:v1
    environment:
      WORDPRESS_DB_HOST: tdd-plugin-db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - wp-data:/var/www/html
#      - ./:/var/www/html/wp-content/plugins/wordpress-tdd-plugin
    networks:
      - net-wp

    ports:
      - 80:80
    depends_on:
      - db-svc

# Persist DB and WordPress data across containers
volumes:
  db-data-mariadb:
  wp-data:
networks:
  net-wp:

